### ISSUE TITLE
SamToFastq to unaligned BAM complains about unpaired mates

### ISSUE THREAD

**Issue by ggabernet** [nf-core/sarek#122]
Hi, when starting `sarek` with unaligned `BAM` files, I get the following error in the `MapReads` process due to `SamToFastq`. 

```Using GATK jar /opt/conda/envs/nf-core-sarek-2.5.2/share/gatk4-4.1.2.0-1/gatk-package-4.1.2.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx372g -jar /opt/conda/envs/nf-core-sarek-2.5.2/share/gatk4-4.1.2.0-1/gatk-package-4.1.2.0-local.jar SamToFastq --INPUT=db2fe200f284c9d024ace1e110d4efa6.CHC1754N.sorted.bam --FASTQ=/dev/stdout --INTERLEAVE=true --NON_PF=true
11:40:52.633 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/conda/envs/nf-core-sarek-2.5.2/share/gatk4-4.1.2.0-1/gatk-package-4.1.2.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Sat Feb 22 11:40:52 UTC 2020] SamToFastq  --INPUT db2fe200f284c9d024ace1e110d4efa6.CHC1754N.sorted.bam --FASTQ /dev/stdout --INTERLEAVE true --INCLUDE_NON_PF_READS true  --OUTPUT_PER_RG false --COMPRESS_OUTPUTS_PER_RG false --RG_TAG PU --RE_REVERSE true --CLIPPING_MIN_LENGTH 0 --READ1_TRIM 0 --READ2_TRIM 0 --INCLUDE_NON_PRIMARY_ALIGNMENTS false --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Sat Feb 22 11:40:52 UTC 2020] Executing as root@ip-172-31-21-99.ec2.internal on Linux 4.14.165-133.209.amzn2.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.2.0
[M::bwa_idx_load_from_disk] read 3171 ALT contigs
[W::main_mem] when '-p' is in use, the second query file is ignored.
[M::process] read 795736 sequences (100000250 bp)...
[M::process] 0 single-end sequences; 795736 paired-end sequences
INFO	2020-02-22 11:40:59	SamToFastq	Processed     1,000,000 records.  Elapsed time: 00:00:07s.  Time for last 1,000,000:    7s.  Last read position: chr1:3,679,276
...
...
INFO	2020-02-22 16:15:53	SamToFastq	Processed 1,004,000,000 records.  Elapsed time: 04:35:00s.  Time for last 1,000,000:   25s.  Last read position: chrY:59,079,046
[Sat Feb 22 16:15:54 UTC 2020] picard.sam.SamToFastq done. Elapsed time: 275.03 minutes.
Runtime.totalMemory()=144277241856
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Found 6534 unpaired mates
	at htsjdk.samtools.SAMUtils.processValidationError(SAMUtils.java:467)
	at picard.sam.SamToFastq.doWork(SamToFastq.java:211)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (2, 449, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (410, 495, 597)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (36, 971)
[M::mem_pestat] mean and std.dev: (496.58, 152.28)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1158)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::process] read 658604 sequences (82750538 bp)...
[M::mem_process_seqs] Processed 795956 reads in 1069.883 CPU sec, 22.743 real sec
[M::process] 0 single-end sequences; 658604 paired-end sequences
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (9, 47804, 251, 4)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (433, 512, 600)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (99, 934)
[M::mem_pestat] mean and std.dev: (515.67, 131.15)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1101)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (1392, 2857, 3468)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 7620)
[M::mem_pestat] mean and std.dev: (2465.89, 1275.67)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 9696)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 658604 reads in 1479.307 CPU sec, 30.950 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -K 100000000 -R @RG\tID:1\tPU:1\tSM:P1N\tLB:P1N\tPL:illumina -t 48 -M -p Homo_sapiens_assembly38.fasta /dev/stdin -
[main] Real time: 16546.077 sec; CPU: 697892.779 sec
[bam_sort_core] merging from 144 files and 48 in-memory blocks...
```

The command executed `command.sh` was:
```#!/bin/bash -euo pipefail
gatk --java-options -Xmx372g SamToFastq --INPUT=db2fe200f284c9d024ace1e110d4efa6.CHC1754N.sorted.bam --FASTQ=/dev/stdout --INTERLEAVE=true --NON_PF=true | \
bwa mem -K 100000000 -R "@RG\tID:1\tPU:1\tSM:P1N\tLB:P1N\tPL:illumina"  -t 48 -M Homo_sapiens_assembly38.fasta         -p /dev/stdin - 2> >(tee db2fe200f284c9d024ace1e110d4efa6.CHC1754N.sorted.bam.bwa.stderr.log >&2) |         samtools sort --threads 48 -m 2G - > P1N_1.bam
```
I found some help from Samtools that in these cases either the BAM can be cleaned of unpaired reads before running SamToFastq or that VALIDATION_STRINGENCY=SILENT flag can be used when running SamToFastq.

Is there any reason why you are not doing that? I can make a PR otherwise to fix that. 

It would also be great to have the SamToFastq step separated from the mapping, so we can cache this process in case the mapping fails. Don't you think?

I'm happy to help if you think this is a good idea!

**Comment by ggabernet** [comment]
I've tested it and with the `VALIDATION_STRINGENCY=SILENT` flag it runs through fine

**Comment by FriederikeHanssen** [comment]
Will move qbic-pipelines/bamtofastq to DSL2 and include it as a sub workflow

**Comment by FriederikeHanssen** [comment]
included a subworkflow for bamtofastq based on qbic-pipelines/bamtofastq using samtools. Should work now. I will therefore close the issue. Feel free to reopen in case of more issues
