### ISSUE TITLE
Strelka malformed VCF header

### ISSUE THREAD

**Issue by gitMakeCoffee** [nf-core/sarek#1352]
### Description of the bug

I have been trying to run Strelka using Sarek. The initial steps (FASTQC, FASTP) seem to run successfully, as well as the actual calling. Unfortunately, it looks like the downstream step of merging Strelka's VCFs into one single VCF causes the pipeline to crash. 

```
Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_SINGLE_STRELKA:MERGE_STRELKA (S-9998)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx3276M -XX:-UsePerfData" \
      MergeVcfs \
      --INPUT S-9998.strelka.chr20_36314720-64334167.variants.vcf.gz --INPUT S-9998.strelka.chr2_16146120-32867130.variants.vcf.gz --INPUT S-9998.strelka.chr6_95070791-167591393.variants.vcf.gz --INPUT S-9998.strelka.chr4_10001-1429358
.variants.vcf.gz --INPUT S-9998.strelka.chr5_139453660-155760324.variants.vcf.gz --INPUT S-9998.strelka.chr11_51078349-54425074.variants.vcf.gz --INPUT S-9998.strelka.chr15_20729747-21193490.variants.vcf.gz --INPUT S-9998.strelka.chr18
_47019913-54536574.variants.vcf.gz --INPUT S-9998.strelka.chr12_37235253-37240944.variants.vcf.gz --INPUT S-9998.strelka.chr1_122026460-124977944.variants.vcf.gz --INPUT S-9998.strelka.chr17_60001-448188.variants.vcf.gz --INPUT S-9998.
strelka.chr13_86252980-111703855.variants.vcf.gz --INPUT S-9998.strelka.chrX_37285838-49348394.variants.vcf.gz --INPUT S-9998.strelka.chr8_44033745-45877265.variants.vcf.gz --INPUT S-9998.strelka.chr4_190173122-190204555.variants.vcf.g
z --INPUT S-9998.strelka.chrY_9055175-9057608.variants.vcf.gz --INPUT S-9998.strelka.chr1_10001-207666.variants.vcf.gz --INPUT S-9998.strelka.chr7_58169654-60828234.variants.vcf.gz --INPUT S-9998.strelka.chr9_41229379-41237752.variants
.vcf.gz --INPUT S-9998.strelka.chr10_39590436-39593013.variants.vcf.gz --INPUT S-9998.strelka.chr2_238904048-242183529.variants.vcf.gz \
      --OUTPUT S-9998.strelka.variants.vcf.gz \
      --SEQUENCE_DICTIONARY Homo_sapiens_assembly38.dict \
      --TMP_DIR . \

 htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file, for input sour
ce: file://S-9998.strelka.chr4_190173122-190204555.variants.vcf.gz
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:264)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:103)
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:128)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:121)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:81)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:145)
        at picard.vcf.MergeVcfs.doWork(MergeVcfs.java:182)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:289)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
  Caused by: htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
        at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:115)
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
        at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:262)
        ... 11 more
```

Checking one of the VCF files' header, seems like there is an issue indeed. There is no #CHROM line, and the last ##contig line is merged with the first variant:
```
##contig=<ID=chrUn_JTFH01000515v1_decoy,length=1548>
##contig=<ID=chrUn_JTFH01000516v1_decoy,length=1546>
##contig=<ID=chrUn_JTFH01000517v1_decoy,length=1541>
##contig=<ID=chrUn_JTFH01000518v1_decoy,length=1536>
##contig=<ID=chrUn_JTFH01000519v1_decoy,length=1533>
##contig=<ID=chrUn_JTFH0100chr4 190174313       .       CGCCCACACCGGCGCGT       C       21      LowDepth;NoPassedVariantGTs     CIGAR=1M16D;RU=GCCCACACCGGCGCGT;REFREP=1;IDREP=0;MQ=1   GT:GQ:GQX:DPI:AD:ADF:ADR:FT:PL  0/1:64:9:2:3,1:3,1:
0,0:LowDepth:61,0,240
chr4    190174547       .       G       C       3       LowGQX;NoPassedVariantGTs       SNVHPOL=2;MQ=3  GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL    0/1:32:0:12:0:7,5:7,5:0,0:0.0:LowGQX:34,0,52
chr4    190175118       .       G       T       3       LowGQX;LowDepth;NoPassedVariantGTs      SNVHPOL=2;MQ=3  GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL    0/1:22:0:2:0:1,1:0,1:1,0:0.0:LowGQX;LowDepth:35,0,20
chr4    190175160       .       C       T       47      LowGQX;LowDepth;NoPassedVariantGTs      SNVHPOL=4;MQ=8  GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL    1/1:5:1:2:0:0,2:0,1:0,1:-9.2:LowGQX;LowDepth:83,6,0
chr4    190175166       .       G       C       48      LowGQX;LowDepth;NoPassedVariantGTs      SNVHPOL=2;MQ=9  GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL    1/1:5:1:2:0:0,2:0,1:0,1:-9.4:LowGQX;LowDepth:84,6,0
```

Is this a known issue?
Thanks

### Command used and terminal output

```console
nextflow run ../../.NEXTFLOW/nf-core-sarek_3.4.0/3_4_0/ -profile singularity,cluster --input sampleSheet.csv --outdir results/  --tools strelka
```

### System information

Nextflow v23.04.3.5875
Ran on HPC with Slurm and Singularity
Sarek v3.4.0

**Comment by maxulysse** [comment]
That's the first time I see this one, so not a known issue for sure, can you share your log, samplesheet and any additional config files you might have used?

**Comment by gitMakeCoffee** [comment]
Forgot to mention this happened during a previous attempt when trying to run along with DeepVariant and FreeBayes. Strelka was the only tool to crash the pipeline that far.

I tried debugging by running Strelka alone.

However, something very strange just happened... I just reran the same command with ```-resume```, looks like the VCF headers have been fixed somehow, and the pipeline is now running...

These are clinical samples, so I'll try my best to share as much as I can.

For the samplesheet, I used the following columns: ```patient,sample,lane,fastq_1,fastq_2```
All paths provided to the pipeline are absolute paths. FASTQs are gzipped, and are correctly processed by FASTQC/Fastp, upstream of Strelka.

Config used is as follows (Canadian cluster):
```
singularity{
  autoMounts = true
}

process {
  executor = 'slurm' 
  pollInterval = '60 sec'
  clusterOptions = '--account=(account name on cluster)'
  submitRateLimit = '60/1min'
  queueSize = 100 
  errorStrategy = 'retry'
  maxRetries = 5
  errorStrategy = { task.exitStatus in [125,139] ? 'retry' : 'finish' }
  memory = { check_max( 8.GB * task.attempt, 'memory' ) }
  cpu = 1  
  time = '3h' 
}

profiles {
  cluster{
    max_memory='1024G'
    max_cpu=128
    max_time='168h'
  }
}
```

Lost the ```.nextflow.log``` as I cleaned up before resuming the pipeline... However, the only obvious error message was the one I posted earlier.
As mentioned , it looks like it's running now that I've resumed it. Will provide updates.
Thank you very much!

**Comment by gitMakeCoffee** [comment]
Unfortunately, the rerun has crashed again. Please find attached the log. You'll find the error message by looking for the key word 'malformed'. I had to remove the lines containing the initial FASTQ file names for confidentiality (the first QC steps run fine though).
[github.log](https://github.com/nf-core/sarek/files/13663036/github.log)

Is this a known issue with Strelka/Sarek?
My FASTQ files have correctly been processed from start to finish by other pipelines, so I'm confused.
Of possible relevance, the compute nodes I'm using do not have access to the Internet. However, all Singularity images have been downloaded prior to running Sarek.
Thank you for your help.
