### ISSUE TITLE
samplesheet issue

### ISSUE THREAD

**Issue by maxulysse** [nf-core/sarek#1567]
Hey, this problem has not been entirely fixed... 
I am running with a local genome with` ignore igenomes` set and have a sample sheet with both status entered: 0 and 1. 
However, this error is still occurring making the workflow un-runnable for version: **nf-core/sarek v3.4.2**

`
nextflow.exception.WorkflowScriptErrorException: 
The sample-sheet only contains tumor-samples, but the following tools,  which were requested by the option "tools", expect at least one normal-sample : haplotypecaller
`

**COMMAND:**

`
nextflow \
    main.nf \
    -c "pfr_profile.config" \
    -profile pfr,singularity \
    -params-file "pfr_params.json" \
	--input ${INPUT} \
    --outdir "${OUT_DIR}" \
	--genome null \
    --igenomes_ignore \
	--wes true \
	--skip_tools baserecalibrator \
	--tools "freebayes,haplotypecaller,mpileup" \
    --fasta ${FASTA} \
    --fasta_fai ${FAI} \
	--dict ${DICT} \
	--trim_fastq true \
	--save_trimmed true \
    --save_reference \
	--save_mapped true \
	--save_output_as_bam true \
    -resume
`

**Note, the pfr profile only specifies SLURM as the executor.**

**pfr_params.jason:**

`
{
	"genome": null,
    "igenomes_ignore": true,
    "save_reference": true,
    "split_fastq": 50000000,
    "trim_fastq": true,
    "save_trimmed": true,
    "aligner": "bwa-mem",
    "save_mapped": true,
    "save_output_as_bam": true
}
`

**Here is the error in the log file:**

`
Jun-14 23:58:10.815 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: slurm
Jun-14 23:58:10.815 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'slurm'
Jun-14 23:58:10.831 [main] DEBUG nextflow.Session - Config process names validation disabled as requested
Jun-14 23:58:10.833 [main] DEBUG nextflow.Session - Igniting dataflow network (184)
Jun-14 23:58:10.844 [Actor Thread 5] ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.NullPointerException: Cannot get property 'baseName' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at Script_48a2d276$_runScript_closure1$_closure2$_closure6.doCall(Script_48a2d276:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Here is the sample sheet:**

`
patient,status,sample,lane,fastq_1,fastq_2

GC,1,GC_CAT13ANXX_TTAGGC,L001,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L001_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L001_R2.fastq.gz
GC,1,GC_CAT13ANXX_TTAGGC,L002,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L002_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L002_R2.fastq.gz
GC,1,GC_CAT13ANXX_TTAGGC,L003,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L003_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_A_GC_CAT13ANXX_TTAGGC_L003_R2.fastq.gz
SW,0,SW_CAT13ANXX_TGACCA,L001,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L001_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L001_R2.fastq.gz
SW,0,SW_CAT13ANXX_TGACCA,L002,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L002_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L002_R2.fastq.gz
SW,0,SW_CAT13ANXX_TGACCA,L003,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L003_R1.fastq.gz,/WGS/AGRF_CAGRF14129_CAT13ANXX/DH_B_SW_CAT13ANXX_TGACCA_L003_R2.fastq.gz
`

_Originally posted by @charlesdavid in https://github.com/nf-core/sarek/issues/1260#issuecomment-2169063980_

**Comment by FriederikeHanssen** [comment]
close as solved. Please reopen if recounter
