### ISSUE TITLE
CNVKIT doesn't accept *.list format interval files

### ISSUE THREAD

**Issue by cmatKhan** [nf-core/sarek#1610]
### Description of the bug

when passing a .list format file, eg

```raw
Chr1:1-1000
```

to `--intervals`,  the CNVKIT step fails

```
ERROR ~ Error executing process > 'NFCORE_SAREK:PREPARE_REFERENCE_CNVKIT:CNVKIT_ANTITARGET (intervals)'

Caused by:
  Process `NFCORE_SAREK:PREPARE_REFERENCE_CNVKIT:CNVKIT_ANTITARGET (intervals)` terminated with an error exit status (1)


Command executed:

  cnvkit.py \
      antitarget \
      intervals.list \
      --output intervals.antitarget.bed \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:PREPARE_REFERENCE_CNVKIT:CNVKIT_ANTITARGET":
      cnvkit: $(cnvkit.py version | sed -e "s/cnvkit v//g")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-c_o_2ofd because the default path (/home/chasem/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Fontconfig error: No writable cache directories
  Traceback (most recent call last):
    File "/usr/local/bin/cnvkit.py", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
      args.func(args)
    File "/usr/local/lib/python3.10/site-packages/cnvlib/commands.py", line 479, in _cmd_antitarget
      targets = tabio.read_auto(args.targets)
    File "/usr/local/lib/python3.10/site-packages/skgenome/tabio/__init__.py", line 103, in read_auto
      fmt = sniff_region_format(infile)
    File "/usr/local/lib/python3.10/site-packages/skgenome/tabio/__init__.py", line 255, in sniff_region_format
      raise ValueError("File %r does not appear to be a recognized "
  ValueError: File 'intervals.list' does not appear to be a recognized format! (Any of: text, tab, interval, refflat, gff, bed)
  First non-blank line:
  CP022325.1:69348-69349
```

### Command used and terminal output

```console
nextflow run nf-core/sarek -r latest --intervals intervals.list ...
```
```


### Relevant files

_No response_

### System information

- Nextflow version: 24.04.2
- Hardware: HPC
- Executor: slurm
- Container engine: Singularity
- OS: Rocky linux
- Version nf-core/sarek: 3.4.2

**Comment by FriederikeHanssen** [comment]
good catch. We should add some validation to make this fail very early
