### ISSUE TITLE
`cnvkit` output files are missing

### ISSUE THREAD

**Issue by bounlu** [nf-core/sarek#1625]
### Description of the bug

`cnvkit` output files are missing. There is no segmentation file `.cns` and scatter and diagram plot files `.pdf` in the output folder. They are not generated by `cnvkit batch` module.

**Comment by bounlu** [comment]
[This](https://github.com/etal/cnvkit/issues/760#issuecomment-2296478429) might be the issue.

**Comment by bounlu** [comment]
When I cd to the work directory and run the `segment` command, it fails as below:

`$ cnvkit.py segment my_sample.cnr -o my_sample.cns`

```
Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cnvlib/core.py", line 23, in call_quiet
    proc = subprocess.run(args, check=True, capture_output=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpk_1h085m')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/cnvlib/commands.py", line 1022, in _cmd_segment
    results = segmentation.do_segmentation(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 81, in do_segmentation
    rets = list(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 126, in _ds
    return _do_segmentation(*args)
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 209, in _do_segmentation
    seg_out = core.call_quiet(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/core.py", line 30, in call_quiet
    raise RuntimeError(
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmpk_1h085m

Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpk_1h085m')' returned non-zero exit status 1.
```

This is the reason why no `.cns` file is generated and the `batch` command is terminated here.

**Comment by etal** [comment]
Is the weight column always entirely null, or sometimes a mix of numeric values and the occasional null?

**Comment by bounlu** [comment]
It's entirely null. I didn't test with different datasets though.

**Comment by etal** [comment]
I merged a possible fix in etal/cnvkit#914 . Are you able to try the latest development version of CNVkit and see if the problem is fixed now, or does the fix for sarek require a stable release of CNVkit first?

**Comment by bounlu** [comment]
I think `sarek` requires a stable release of CNVkit first so that it can be pulled as an image.

However, I see your temporary fix is to replace the weight column by 1 if it's null and it will work as I tested, but it should be better to understand why it is null at the first place and what causes a null weight column. I think manually replacing the weight column may cause misleading results?

**Comment by bounlu** [comment]
> Is the weight column always entirely null, or sometimes a mix of numeric values and the occasional null?

Ok I tested with your PR, now those samples with entirely null column for weight works and the next steps are processed by the `batch` command, however those with partially null values still have the expected output files missing.

**Comment by lconde-ucl** [comment]
I'm having the same issue with cnvkit not providing the output files *for the normals*. It provides the somatic results, but it fails when doing germline calling in the normals.  

@FriederikeHanssen, I think that the full tests that you referred to might have failed too. All the output files are generated in the HCC1395T_vs_HCC1395N folder:

https://nf-co.re/sarek/3.4.3/results/sarek/results-e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/test_full_aws/variant_calling/cnvkit/HCC1395T_vs_HCC1395N/

but not in the HCC1395N folder (no .cns or .png files for example):

https://nf-co.re/sarek/3.4.3/results/sarek/results-e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/test_full_aws/variant_calling/cnvkit/HCC1395N/

As comparison, the test_full_germline_aws seemed to have run successfully: 
https://nf-co.re/sarek/3.4.3/results/sarek/results-e92242ead3dff8e24e13adbbd81bfbc0b6862e4c/test_full_germline_aws/variant_calling/cnvkit/NA12878/

The temporary fix mentioned by @bounlu and @etal works. From what I can see, all the empty values are always associated to an antitarget entry in the .cnr file, so I'm guessing it only fails for WES data (but not for WGS/amplicon and these would not use antitargets?)
