### ISSUE TITLE
No such property: enable for class: java.lang.String - nextflow.enable.configProcessNamesValidation problem

### ISSUE THREAD

**Issue by allyssonallan** [nf-core/sarek#1723]
### Description of the bug

Hi sarekers,

I am getting problem with:

`No such property: enable for class: java.lang.String`

Solution:

I commented this debug line in `nextflow.config` and it worked:

```
// Disable process selector warnings by default. Use debug profile to enable warnings.
// nextflow.enable.configProcessNamesValidation = false
```

In some way the change in [nextflow/#2700](https://github.com/nextflow-io/nextflow/issues/2700) is affected by java version.

### Command used and terminal output

nextflow run nf-core/sarek -r 3.4.4 -profile test

### Relevant files

Nov-02 17:10:34.806 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test`
Nov-02 17:10:36.629 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '~/.nextflow/assets/nf-core/sarek/nextflow.config'

  No such property: enable for class: java.lang.String

groovy.lang.MissingPropertyException: No such property: enable for class: java.lang.String
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at _nf_config_6dcc87d5.run(_nf_config_6dcc87d5:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:457)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:486)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:312)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:439)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:425)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:375)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:320)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:818)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:831)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:332)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:658)

### System information

info
  
```
  Version: 24.10.0 build 5928
  Created: 27-10-2024 18:36 UTC (15:36 BRST)
  System: Linux 4.18.0-477.10.1.el8_8.x86_64
  Runtime: Groovy 4.0.23 on OpenJDK 64-Bit Server VM 17.0.10+7
  Encoding: UTF-8 (UTF-8)
```

HPC - slurm:

```
Linux 4.18.0-477.10.1.el8_8.x86_64 #1 SMP Tue May 16 11:38:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asp8200** [comment]
I have no problem with running the test-profile of Sarek v3.4.4 with singularity or docker:
```
nextflow run nf-core/sarek -r 3.4.4 -profile test,singularity --outdir results
nextflow run nf-core/sarek -r 3.4.4 -profile test,docker --outdir results
```
using Nextflow v24.10.0.

When trying to run the nf-command from description if the issue, I get the error msg `* Missing required parameter: --outdir` which is to be expected.

**Comment by allyssonallan** [comment]
> I have no problem with running the test-profile of Sarek v3.4.4 with singularity or docker:
> 
> ```
> nextflow run nf-core/sarek -r 3.4.4 -profile test,singularity --outdir results
> nextflow run nf-core/sarek -r 3.4.4 -profile test,docker --outdir results
> ```
> 
> using Nextflow v24.10.0.
> 
> When trying to run the nf-command from description if the issue, I get the error msg `* Missing required parameter: --outdir` which is to be expected.

Interesting, the behavior was before they call the nf-params.json where we point to the `output` flag, the `test` profile was only to illustrate. It could be also a weird behavior due to the process and login nodes, I have to investigate this.

How it is working: 

I submit the job via sbatch, the instant response appear to me: 'No such property: enable for class: java.lang.String' in nextflow.log. After the comment this line `// nextflow.enable.configProcessNamesValidation = false` the pipe smoothly works.

**Comment by allyssonallan** [comment]
I will close this issue, if somebody is struggling in the same part, please reopen here and comment it. Thanks for your help @asp8200 !
