### ISSUE TITLE
Update Mutect2 version to 4.1.7.0

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/sarek#210]
I ran sarek with `mutect2` and ran into this: 
```Runtime.totalMemory()=934281216
  java.lang.IllegalStateException: Smith-Waterman alignment failure. Cigar = 219M with reference length 219 but expecting reference length of 275 ref = TGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCGCCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCGCCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCACCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCATGAGCACCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTCTGACTTCCACGCTGG path TGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCGCCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCACCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTGGCCTCACGAGCACCGCTGGGTGCCTGAGCACCTGCCCCACCAGAGCGCCACTGCTCTGACTTCCACGCTGG
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.findBestPaths(ReadThreadingAssembler.java:354)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.assembleKmerGraphsAndHaplotypeCall(ReadThreadingAssembler.java:196)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.readthreading.ReadThreadingAssembler.runLocalAssembly(ReadThreadingAssembler.java:146)
        at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.AssemblyBasedCallerUtils.assembleReads(AssemblyBasedCallerUtils.java:269)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:226)
        at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:299)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:200)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:173)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

Looks like this is a known issue (https://github.com/broadinstitute/gatk/issues/6533) and fixed in the new release 4.1.7 : https://github.com/broadinstitute/gatk/releases

**Comment by FriederikeHanssen** [comment]
Will close this issue as it was fixed
