### ISSUE TITLE
Malformed tsv file

### ISSUE THREAD

**Issue by yaowei2010** [nf-core/sarek#286]
I got a error message that I cannot not run the nextflow anymore.
This error is caused by `Cannot invoke method toInteger() on null object`

Can anyone help this issue?

the log is following:

```
Sep-30 17:54:29.985 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/sarek --input /mscdb/bioinfo/hts/ineo/sample.tsv -profile docker --fasta /home/bioinfo/ngs/References/b37/human_g1k_v37_decoy.fasta --dict /home/bioinfo/ngs/References/b37/human_g1k_v37_decoy.dict --fasta_fai /home/bioinfo/ngs/References/b37/human_g1k_v37_decoy.fasta.fai --bwa '/home/bioinfo/ngs/References/b37/human_g1k_v37_decoy.fasta.64.{amb,ann,bwt,pac,sa}' --dbsnp /home/bioinfo/ngs/References/b37/dbsnp_138.b37.vcf --dbsnp_index /home/bioinfo/ngs/References/b37/dbsnp_138.b37.vcf.idx --known_indels /home/bioinfo/ngs/References/b37/Mills_and_1000G_gold_standard.indels.b37.vcf --known_indels_index /home/bioinfo/ngs/References/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.idx --genome GRCh37 -resume --tools HaplotypeCaller --max_cpus 8 --max_memory 24GB -with-report --sequencing_center GGA --max_time 168h --skip_qc all
Sep-30 17:54:30.395 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.04.1
Sep-30 17:54:32.722 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/bioinfo/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/sarek.git
Sep-30 17:54:32.749 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/bioinfo/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/sarek.git
Sep-30 17:54:33.093 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/bioinfo/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/sarek.git
Sep-30 17:54:33.093 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/sarek` [maniac_lichterman] - revision: bce378e09d [master]
Sep-30 17:54:34.832 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/bioinfo/.nextflow/assets/nf-core/sarek/nextflow.config
Sep-30 17:54:34.833 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/bioinfo/.nextflow/assets/nf-core/sarek/nextflow.config
Sep-30 17:54:34.864 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `docker`
Sep-30 17:54:37.362 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, denbi_qbic, bi, genotoul, bigpurple, test_trimming, test_annotation, uppmax, test_tool, docker, gis, utd_ganymede, conda, singularity, icr_davros, munin, prince, czbiohub_aws, hebbe, cfc, uzh, ccga_med, debug, test, genouest, cbe, ebc, ccga_dx, crick, google, test_split_fastq, kraken, phoenix, shh, test_no_gatk_spark, awsbatch, pasteur, uct_hpc, test_targeted, binac]
Sep-30 17:54:37.642 [main] DEBUG nextflow.Session - Session uuid: 62fe3436-8d20-450b-8d7b-f08e174753e5
Sep-30 17:54:37.643 [main] DEBUG nextflow.Session - Run name: maniac_lichterman
Sep-30 17:54:37.645 [main] DEBUG nextflow.Session - Executor pool size: 24
Sep-30 17:54:37.683 [main] DEBUG nextflow.cli.CmdRun -
  Version: 20.04.1 build 5335
  Created: 03-05-2020 19:37 UTC (04-05-2020 03:37 CDT)
  System: Linux 3.10.0-1127.13.1.el7.x86_64
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 1.8.0_252-b09
  Encoding: UTF-8 (UTF-8)
  Process: 10946@MSC-Mining01 [192.168.7.12]
  CPUs: 24 - Mem: 30.9 GB (559.4 MB) - Swap: 15.6 GB (13.1 GB)
Sep-30 17:54:37.786 [main] DEBUG nextflow.Session - Work-dir: /mscdb/bioinfo/hts/ineo/work [xfs]
Sep-30 17:54:37.891 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Sep-30 17:54:37.894 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-30 17:54:38.569 [main] DEBUG nextflow.Session - Session start invoked
Sep-30 17:54:38.576 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /mscdb/bioinfo/hts/ineo/results/pipeline_info/execution_trace.txt
Sep-30 17:54:44.236 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-30 17:54:44.270 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: FreebayesSingle, VEP, Mpileup, MapReads, MergeMutect2Stats, ApplyBQSR, IndexBamRecal, Ascat, AlleleCounter, Vcftools, Sentieon_BQSR, BuildGermlineResourceIndex, TrimGalore, Snpeff, BuildKnownIndelsIndex, StrelkaSingle, Sentieon_TNscope, HaplotypeCaller, Sentieon_DNAseq, StrelkaBP, Output_documentation, ControlFREEC, BuildIntervals, PileupSummariesForMutect2, MantaSingle, BuildPonIndex, ControlFreecViz, CompressVCFvep, BuildFastaFai, CalculateContamination, VEPmerge, IndexBamFile, BcftoolsStats, Strelka, MergePileupSummaries, IndexBamMergedForSentieon, MergeBamMapped, BuildDict, FastQCFQ, Manta, BamQC, GenotypeGVCFs, CompressVCFsnpEff, CreateIntervalBeds, MergeMpileup, Get_software_versions, GatherBQSRReports, BuildDbsnpIndex, TIDDIT, FastQCBAM, MarkDuplicates, MSIsensor_msi, BaseRecalibrator, CNVkit, MultiQC, MergeBamRecal, SamtoolsStats, BuildBWAindexes, FreeBayes, CompressSentieonVCF, ConvertAlleleCounts, Sentieon_MapReads, Mutect2, ConcatVCF, Sentieon_DNAscope, FilterMutect2Calls, MSIsensor_scan, Sentieon_Dedup, ConcatVCF_Mutect2
Sep-30 17:54:44.728 [Actor Thread 2] ERROR nextflow.extension.OperatorEx - @unknown
java.lang.NullPointerException: **Cannot invoke method toInteger() on null object**
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:43)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at Script_9abbae70$_extractFastq_closure9.doCall(Script_9abbae70:4175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
        at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
        at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
        at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
        at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
        at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Sep-30 17:54:44.741 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Sep-30 17:54:44.788 [Actor Thread 2] DEBUG nextflow.Session - Session aborted -- Cause: Cannot invoke method toInteger() on null object
Sep-30 17:54:44.788 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {}
Sep-30 17:54:44.849 [Actor Thread 2] DEBUG nextflow.Session - The following nodes are still active:
  [operator] map
  [operator] map
```

EDIT: code block for Markdown

**Comment by MaxUlysse** [comment]
Hi @yaowei2010 thanks a lot for your interest in Sarek, I'm sorry you're having issues.

I'll have a look right now, and will probably ask you for more details.

All the best,
Maxime

**Comment by MaxUlysse** [comment]
Can you try this command line instead?
```
nextflow run nf-core/sarek -profile docker --input /mscdb/bioinfo/hts/ineo/sample.tsv \
--genome GRCh37 --igenomes_ignore --genomes_base home/bioinfo/ngs/References/b37
--tools HaplotypeCaller --max_cpus 8 --max_memory 24GB -with-report \
--sequencing_center GGA --max_time 168h --skip_qc all
```

**Comment by yaowei2010** [comment]
Hi, Maxime

Similar error I got it.

N E X T F L O W  ~  version 20.04.1
Launching `nf-core/sarek` [sleepy_brown] - revision: bce378e09d [master]
Cannot invoke method toInteger() on null object

 -- Check script '/home/bioinfo/.nextflow/assets/nf-core/sarek/main.nf' at
line: 4175 or see '.nextflow.log' file for more details



[image: image.png]

Thanks for your support!

Willis Cheng

GGA

**Comment by MaxUlysse** [comment]
ok, then can you send your tsv file?

**Comment by yaowei2010** [comment]
Thanks

Here you are.


Willis

**Comment by yaowei2010** [comment]
OK I attach the file here.

Thanks

[sample.zip](https://github.com/nf-core/sarek/files/5305200/sample.zip)

**Comment by MaxUlysse** [comment]
I removed the empty lines at the end, and converted all the spaces into tabs:
This one should work:

[sample_MG.tsv.zip](https://github.com/nf-core/sarek/files/5305233/sample_MG.tsv.zip)

**Comment by yaowei2010** [comment]
Ok, it works!!!

Thanks. Maybe it is my fault that I made a failed text files...

**Comment by MaxUlysse** [comment]
That happens.
I'll try to make a better check of the tsv file so the error message is more understandable.
