### ISSUE TITLE
Unexpected error [UnsupportedOperationException] when running the test case

### ISSUE THREAD

**Issue by shaojunyu** [nf-core/sarek#799]
### Description of the bug

Unexpected error [UnsupportedOperationException] when running the test case

### Command used and terminal output

```console
$ nextflow run nf-core/sarek -profile test_full,docker --outdir out
```

### Relevant files

Oct-14 12:07:56.647 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/sarek -profile test_full,docker --outdir out
Oct-14 12:07:56.699 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.10.6
Oct-14 12:07:57.456 [main] DEBUG nextflow.scm.AssetManager - Git config: /users/syu86/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/sarek.git
Oct-14 12:07:57.466 [main] DEBUG nextflow.scm.AssetManager - Git config: /users/syu86/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/sarek.git
Oct-14 12:07:57.529 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/sarek` [festering_volta] - revision: bcd7bf9cb9 [master]
Oct-14 12:07:57.873 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /users/syu86/.nextflow/assets/nf-core/sarek/nextflow.config
Oct-14 12:07:57.873 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mydata/nf_gwas/nextflow.config
Oct-14 12:07:57.873 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /users/syu86/.nextflow/assets/nf-core/sarek/nextflow.config
Oct-14 12:07:57.873 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mydata/nf_gwas/nextflow.config
Oct-14 12:07:57.880 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test_full,docker`
Oct-14 12:07:58.133 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Oct-14 12:07:58.141 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Oct-14 12:07:58.142 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Oct-14 12:07:58.144 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Oct-14 12:07:58.147 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Oct-14 12:07:58.307 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Oct-14 12:07:58.307 [main] DEBUG nextflow.plugin.PluginsFacade - Using Default plugins manager
Oct-14 12:07:59.148 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test_full,docker`
Oct-14 12:07:59.163 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, alice, mjolnir_globe, uppmax, lugh, test_full_germline, unibe_ibu, vai, czbiohub_aws, jax, ccga_med, tigem, google, use_gatk_spark, eddie, medair, alignment_to_fastq, bi, bigpurple, sbc_sharc, adcra, cedars, tools, utd_ganymede, charliecloud, targeted, icr_davros, save_bam_mapped, munin, rosalind, hasta, annotation, cfc, uzh, split_fastq, ebc, ku_sund_dangpu, ccga_dx, variantcalling_channels, crick, recalibrate_bam, marvin, biohpc_gen, shifter, mana, mamba, awsbatch, imperial, maestro, skip_bqsr, genotoul, skip_markduplicates, abims, nihbiowulf, nu_genomics, oist, sahmri, mpcdf, leicester, vsc_ugent, sage, trimming, cambridge, tools_tumoronly, podman, cheaha, test, prepare_recalibration_bam, computerome, tools_germline, seg_globe, sanger, tools_somatic_ascat, pasteur, test_full, azurebatch, hki, crukmi, docker, gis, umi, eva, markduplicates_bam, fgcz, conda, singularity, prince, hebbe, utd_sysbio, debug, genouest, tools_somatic, cbe, markduplicates_cram, recalibrate_cram, no_intervals, prepare_recalibration_cram, pair, phoenix, gitpod, uct_hpc, aws_tower, binac]
Oct-14 12:07:59.196 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/users/syu86/.nextflow/plugins
Oct-14 12:07:59.197 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Oct-14 12:07:59.200 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Oct-14 12:07:59.200 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Oct-14 12:07:59.201 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Oct-14 12:07:59.208 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Oct-14 12:07:59.248 [main] DEBUG nextflow.Session - Session uuid: b179f581-bd07-4059-b472-25858bdfa43e
Oct-14 12:07:59.248 [main] DEBUG nextflow.Session - Run name: festering_volta
Oct-14 12:07:59.249 [main] DEBUG nextflow.Session - Executor pool size: 144
Oct-14 12:07:59.274 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC (09:55 MDT)
  System: Linux 5.4.0-100-generic
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
  Encoding: UTF-8 (UTF-8)
  Process: 125630@node0.syu86-135964.latencymodel-pg0.clemson.cloudlab.us [130.127.134.38]
  CPUs: 144 - Mem: 251.2 GB (209.9 GB) - Swap: 3 GB (3 GB)
Oct-14 12:07:59.284 [main] DEBUG nextflow.Session - Work-dir: /mydata/nf_gwas/work [ext2/ext3]
Oct-14 12:07:59.284 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /users/syu86/.nextflow/assets/nf-core/sarek/bin
Oct-14 12:07:59.291 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Oct-14 12:07:59.299 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Oct-14 12:07:59.398 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 145; maxThreads: 1000
Oct-14 12:07:59.456 [main] DEBUG nextflow.Session - Session start invoked
Oct-14 12:07:59.461 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /mydata/nf_gwas/out/pipeline_info/execution_trace_2022-10-14_12-07-58.txt
Oct-14 12:07:59.469 [main] DEBUG nextflow.Session - Using default localLib path: /users/syu86/.nextflow/assets/nf-core/sarek/lib
Oct-14 12:07:59.472 [main] DEBUG nextflow.Session - Adding to the classpath library: /users/syu86/.nextflow/assets/nf-core/sarek/lib
Oct-14 12:07:59.473 [main] DEBUG nextflow.Session - Adding to the classpath library: /users/syu86/.nextflow/assets/nf-core/sarek/lib/nfcore_external_java_deps.jar
Oct-14 12:08:00.178 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-14 12:08:00.376 [main] INFO  nextflow.Nextflow - 

-[2m----------------------------------------------------[0m-
                                        [0;32m,--.[0;30m/[0;32m,-.[0m
[0;34m        ___     __   __   __   ___     [0;32m/,-._.--~'[0m
[0;34m  |\ | |__  __ /  ` /  \ |__) |__         [0;33m}  {[0m
[0;34m  | \| |       \__, \__/ |  \ |___     [0;32m\`-._,-`-,[0m
                                        [0;32m`._,._,'[0m
[0;37m      ____[0m
[0;37m    .´ _  `.[0m
[0;37m   /  [0;32m|\[0m`-_ \[0m     [0;34m __        __   ___     [0m
[0;37m  |   [0;32m| \[0m  `-|[0m    [0;34m|__`  /\  |__) |__  |__/[0m
[0;37m   \ [0;32m|   \[0m  /[0m     [0;34m.__| /¯¯\ |  \ |___ |  \[0m
[0;37m    `[0;32m|[0m____[0;32m\[0m´[0m

[0;35m  nf-core/sarek v3.0.2[0m
-[2m----------------------------------------------------[0m-
[1mCore Nextflow options[0m
  [0;34mrevision                  : [0;32mmaster[0m
  [0;34mrunName                   : [0;32mfestering_volta[0m
  [0;34mcontainerEngine           : [0;32mdocker[0m
  [0;34mlaunchDir                 : [0;32m/mydata/nf_gwas[0m
  [0;34mworkDir                   : [0;32m/mydata/nf_gwas/work[0m
  [0;34mprojectDir                : [0;32m/users/syu86/.nextflow/assets/nf-core/sarek[0m
  [0;34muserName                  : [0;32msyu86[0m
  [0;34mprofile                   : [0;32mtest_full,docker[0m
  [0;34mconfigFiles               : [0;32m/users/syu86/.nextflow/assets/nf-core/sarek/nextflow.config, /mydata/nf_gwas/nextflow.config[0m

[1mInput/output options[0m
  [0;34minput                     : [0;32mhttps://raw.githubusercontent.com/nf-core/test-datasets/sarek/testdata/csv/HCC1395_WXS_somatic_full_test.csv[0m
  [0;34moutdir                    : [0;32mout[0m

[1mMain options[0m
  [0;34msplit_fastq               : [0;32m20000000[0m
  [0;34mwes                       : [0;32mtrue[0m
  [0;34mintervals                 : [0;32ms3://nf-core-awsmegatests/sarek/input/S07604624_Padded_Agilent_SureSelectXT_allexons_V6_UTR.bed[0m
  [0;34mtools                     : [0;32mstrelka,mutect2,freebayes,ascat,manta,cnvkit,tiddit,controlfreec,vep[0m

[1mVariant Calling[0m
  [0;34mpon                       : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/1000g_pon.hg38.vcf.gz[0m
  [0;34mpon_tbi                   : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/1000g_pon.hg38.vcf.gz.tbi[0m

[1mReference genome options[0m
  [0;34mascat_genome              : [0;32mhg38[0m
  [0;34mascat_alleles             : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_alleles_hg38.zip[0m
  [0;34mascat_loci                : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_loci_hg38.zip[0m
  [0;34mascat_loci_gc             : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/GC_G1000_hg38.zip[0m
  [0;34mascat_loci_rt             : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/RT_G1000_hg38.zip[0m
  [0;34mbwa                       : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAIndex/[0m
  [0;34mbwamem2                   : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/BWAmem2Index/[0m
  [0;34mchr_dir                   : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/Chromosomes[0m
  [0;34mdbsnp                     : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz[0m
  [0;34mdbsnp_tbi                 : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz.tbi[0m
  [0;34mdbsnp_vqsr                : [0;32m--resource:dbsnp,known=false,training=true,truth=false,prior=2.0 dbsnp_146.hg38.vcf.gz[0m
  [0;34mdict                      : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.dict[0m
  [0;34mdragmap                   : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/dragmap/[0m
  [0;34mfasta                     : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta[0m
  [0;34mfasta_fai                 : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta.fai[0m
  [0;34mgermline_resource         : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/af-only-gnomad.hg38.vcf.gz[0m
  [0;34mgermline_resource_tbi     : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/af-only-gnomad.hg38.vcf.gz.tbi[0m
  [0;34mknown_indels              : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/{Mills_and_1000G_gold_standard.indels.hg38,beta/Homo_sapiens_assembly38.known_indels}.vcf.gz[0m
  [0;34mknown_indels_tbi          : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/{Mills_and_1000G_gold_standard.indels.hg38,beta/Homo_sapiens_assembly38.known_indels}.vcf.gz.tbi[0m
  [0;34mknown_indels_vqsr         : [0;32m--resource:gatk,known=false,training=true,truth=true,prior=10.0 Homo_sapiens_assembly38.known_indels.vcf.gz --resource:mills,known=false,training=true,truth=true,prior=10.0 Mills_and_1000G_gold_standard.indels.hg38.vcf.gz[0m
  [0;34mknown_snps                : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/1000G_omni2.5.hg38.vcf.gz[0m
  [0;34mknown_snps_tbi            : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/GATKBundle/1000G_omni2.5.hg38.vcf.gz.tbi[0m
  [0;34mknown_snps_vqsr           : [0;32m--resource:1000G,known=false,training=true,truth=true,prior=10.0 1000G_omni2.5.hg38.vcf.gz[0m
  [0;34mmappability               : [0;32ms3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/Control-FREEC/out100m2_hg38.gem[0m
  [0;34msnpeff_db                 : [0;32mGRCh38.105[0m
  [0;34msnpeff_genome             : [0;32mGRCh38[0m
  [0;34msnpeff_version            : [0;32m5.1[0m
  [0;34mvep_genome                : [0;32mGRCh38[0m
  [0;34mvep_species               : [0;32mhomo_sapiens[0m
  [0;34mvep_cache_version         : [0;32m106[0m
  [0;34mvep_version               : [0;32m106.1[0m
  [0;34migenomes_base             : [0;32ms3://ngi-igenomes/igenomes[0m

[1mInstitutional config options[0m
  [0;34mconfig_profile_name       : [0;32mFull test profile[0m
  [0;34mconfig_profile_description: [0;32mFull test dataset to check pipeline function[0m

!! Only displaying parameters that differ from the pipeline defaults !!
-[2m----------------------------------------------------[0m-
If you use nf-core/sarek for your analysis please cite:

* The pipeline
  https://doi.org/10.12688/f1000research.16665.2
  https://doi.org/10.5281/zenodo.4468605

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/sarek/blob/master/CITATIONS.md
-[2m----------------------------------------------------[0m-
Oct-14 12:08:01.365 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.3.4
Oct-14 12:08:01.372 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.3.4' resolved
Oct-14 12:08:01.372 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.3.4'
Oct-14 12:08:01.382 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.3.4
Oct-14 12:08:01.393 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Oct-14 12:08:01.394 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38/Annotation/ASCAT/G1000_alleles_hg38.zip
Oct-14 12:08:01.399 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Oct-14 12:08:01.403 [main] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /users/syu86/.aws/credentials
Oct-14 12:08:01.405 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=6bGt7Y.., max_error_retry=5, access_key=AKIAXL..}
Oct-14 12:08:05.710 [main] DEBUG nextflow.file.FileHelper - Path matcher not defined by 'S3FileSystem' file system -- using default default strategy
Oct-14 12:08:05.715 [main] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.UnsupportedOperationException
Oct-14 12:08:05.726 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.UnsupportedOperationException: null
	at com.upplication.s3fs.S3FileSystemProvider.getFileAttributeView(S3FileSystemProvider.java:666)
	at java.base/java.nio.file.Files.getFileAttributeView(Files.java:1776)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:221)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:282)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:328)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2792)
	at nextflow.file.FileHelper.visitFiles(FileHelper.groovy:797)
	at nextflow.file.FileHelper$visitFiles$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
	at nextflow.Nextflow.fileNamePattern(Nextflow.groovy:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:249)
	at nextflow.Nextflow.file(Nextflow.groovy:167)
	at nextflow.Nextflow$file.callStatic(Unknown Source)
	at Script_28ace5fe.runScript(Script_28ace5fe:55)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_c05744b2.runScript(Script_c05744b2:79)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

### System information

- Nextflow version : 21.10.6.5660
- Hardware : HPC
- Executor : local
- Container engine: Docker
- OS : Ubuntu 20.04
- Version of nf-core/sarek : 3.0.2

**Comment by shaojunyu** [comment]
updating to Java 18 solved this problem
