### ISSUE TITLE
segmentation fles are empty

### ISSUE THREAD

**Issue by paumarc** [nf-core/sarek#800]
### Description of the bug

 I having the following error running sarek, at the beginning i thought it was due to some problem with samplefile but I don't see what is wrong there
Error executing process > 'NFCORE_SAREK:sarek:TUMOR_ONLY_VARIANT_CALLING:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:CALCULATECONTAMINATION (L21-6580)'

Caused by:
  Process `NFCORE_SAREK:sarek:TUMOR_ONLY_VARIANT_CALLING:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:CALCULATECONTAMINATION (L21-6580)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx48g" CalculateContamination \
      --input L21-6580.mutect2.pileupsummaries.table \
      --output L21-6580.mutect2.contamination.table \
       \
      --tmp-dir . \
      -tumor-segmentation L21-6580.mutect2.segmentation.table
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:sarek:TUMOR_ONLY_VARIANT_CALLING:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:CALCULATECONTAMINATION":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  3

Command output:
  (empty)

Command error:
  Using GATK jar /usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx48g -jar /usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar CalculateContamination --input L21-6580.mutect2.pileupsummaries.table --output L21-6580.mutect2.contamination.table --tmp-dir . -tumor-segmentation L21-6580.mutect2.segmentation.table
  14:15:35.997 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.2.6.1-0/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
  14:15:36.071 INFO  CalculateContamination - ------------------------------------------------------------
  14:15:36.072 INFO  CalculateContamination - The Genome Analysis Toolkit (GATK) v4.2.6.1
  14:15:36.072 INFO  CalculateContamination - For support and documentation go to https://software.broadinstitute.org/gatk/
  14:15:36.072 INFO  CalculateContamination - Executing as lab@7572d1f7f25e on Linux v5.15.0-50-generic amd64
  14:15:36.072 INFO  CalculateContamination - Java runtime: OpenJDK 64-Bit Server VM v11.0.9.1-internal+0-adhoc..src
  14:15:36.072 INFO  CalculateContamination - Start Date/Time: October 14, 2022 at 2:15:35 PM GMT
  14:15:36.072 INFO  CalculateContamination - ------------------------------------------------------------
  14:15:36.072 INFO  CalculateContamination - ------------------------------------------------------------
  14:15:36.072 INFO  CalculateContamination - HTSJDK Version: 2.24.1
  14:15:36.072 INFO  CalculateContamination - Picard Version: 2.27.1
  14:15:36.073 INFO  CalculateContamination - Built for Spark Version: 2.4.5
  14:15:36.073 INFO  CalculateContamination - HTSJDK Defaults.COMPRESSION_LEVEL : 2
  14:15:36.073 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
  14:15:36.073 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
  14:15:36.073 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
  14:15:36.073 INFO  CalculateContamination - Deflater: IntelDeflater
  14:15:36.073 INFO  CalculateContamination - Inflater: IntelInflater
  14:15:36.073 INFO  CalculateContamination - GCS max retries/reopens: 20
  14:15:36.073 INFO  CalculateContamination - Requester pays: disabled
  14:15:36.073 INFO  CalculateContamination - Initializing engine
  14:15:36.073 INFO  CalculateContamination - Done initializing engine
  14:15:36.097 INFO  CalculateContamination - Shutting down engine
  [October 14, 2022 at 2:15:36 PM GMT] org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination done. Elapsed time: 0.00 minutes.
  Runtime.totalMemory()=1056964608
  java.lang.IllegalArgumentException: Null object is not allowed here.
  	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:643)
  	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:631)
  	at org.broadinstitute.hellbender.utils.tsv.TableWriter.writeMetadata(TableWriter.java:183)
  	at org.broadinstitute.hellbender.tools.walkers.contamination.MinorAlleleFractionRecord.writeToFile(MinorAlleleFractionRecord.java:48)
  	at org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination.doWork(CalculateContamination.java:128)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
  	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
  	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
  	at org.broadinstitute.hellbender.Main.main(Main.java:289)

Work dir:
  /home/lab/Documentos/20220808_MCrespo_22LLC/work/38/7f5f81b38ffe6a89cf9e91265d1a37

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
the sample file looks like

patient,sample,status,lane,fastq_1,fastq_2
L21-6583,L21-6583,1,1,./data/L21-6583_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6583_TTTTTT_l000_R2_001.fastq.gz
L21-6569,L21-6569,1,1,./data/L21-6569_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6569_TTTTTT_l000_R2_001.fastq.gz
L21-6581,L21-6581,1,1,./data/L21-6581_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6581_TTTTTT_l000_R2_001.fastq.gz
L21-6563,L21-6563,1,1,./data/L21-6563_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6563_TTTTTT_l000_R2_001.fastq.gz
L21-6567,L21-6567,1,1,./data/L21-6567_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6567_TTTTTT_l000_R2_001.fastq.gz
L21-6565,L21-6565,1,1,./data/L21-6565_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6565_TTTTTT_l000_R2_001.fastq.gz
L21-6579,L21-6579,1,1,./data/L21-6579_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6579_TTTTTT_l000_R2_001.fastq.gz
L21-6575,L21-6575,1,1,./data/L21-6575_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6575_TTTTTT_l000_R2_001.fastq.gz
L21-6577,L21-6577,1,1,./data/L21-6577_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6577_TTTTTT_l000_R2_001.fastq.gz
L21-6571,L21-6571,1,1,./data/L21-6571_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6571_TTTTTT_l000_R2_001.fastq.gz
L21-6573,L21-6573,1,1,./data/L21-6573_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6573_TTTTTT_l000_R2_001.fastq.gz
L21-6568,L21-6568,1,1,./data/L21-6568_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6568_TTTTTT_l000_R2_001.fastq.gz
L21-6582,L21-6582,1,1,./data/L21-6582_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6582_TTTTTT_l000_R2_001.fastq.gz
L21-6580,L21-6580,1,1,./data/L21-6580_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6580_TTTTTT_l000_R2_001.fastq.gz
L21-6566,L21-6566,1,1,./data/L21-6566_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6566_TTTTTT_l000_R2_001.fastq.gz
L21-6564,L21-6564,1,1,./data/L21-6564_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6564_TTTTTT_l000_R2_001.fastq.gz
L21-6562,L21-6562,1,1,./data/L21-6562_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6562_TTTTTT_l000_R2_001.fastq.gz
L21-6578,L21-6578,1,1,./data/L21-6578_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6578_TTTTTT_l000_R2_001.fastq.gz
L21-6570,L21-6570,1,1,./data/L21-6570_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6570_TTTTTT_l000_R2_001.fastq.gz
L21-6572,L21-6572,1,1,./data/L21-6572_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6572_TTTTTT_l000_R2_001.fastq.gz
L21-6574,L21-6574,1,1,./data/L21-6574_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6574_TTTTTT_l000_R2_001.fastq.gz
L21-6576,L21-6576,1,1,./data/L21-6576_TTTTTT_l000_R1_001.fastq.gz,./data/L21-6576_TTTTTT_l000_R2_001.fastq.gz
SampleSheet.csv (END)
and files  L21-6580.mutect2.pileupsummaries.table and L21-6580.mutect2.segmentation.table are empties

### Command used and terminal output

```console
nextflow run nf-core/sarek -profile docker --input SampleSheet.csv --genome hg19 -r 3.0.2 -c sarek.conf --intervals projectInfo/Target_regions_genes_chr.bed  --known_indels Homo_sapiens_assembly19.known_indels.vcf.gz --pon somatic-b37_Mutect2-WGS-panel-b37_chr.vcf.gz --germline_resource Mills_and_1000G_gold_standard.indels.b37.vcf.gz"

def check_max(obj) {
   try {
        if (obj.compareTo(params.max_memory as nextflow.util.MemoryUnit) == 1)
            return params.max_memory as nextflow.util.MemoryUnit
        else
            return obj
    } catch (all) {
        println "   ### ERROR ###   Max memory '${params.max_memory}' is not valid! Using default value: $obj"
        return obj
    }
}

params {
    max_cpus = 20 
    max_time = 12.h
    max_memory=62.Gb 
    trim_fastq = true
    tools = 'mutect2,snpeff'
    intervals = 'projectInfo/Target_regions_genes_chr.bed'
    config_profile_description = 'bioinfo config'
    config_profile_contact = 'paumarc paumarc@vhio.net'
    config_profile_url = "tobecopiedingithub"


}

process {
    errorStrategy = 'retry'
    maxErrors = '-1'
    maxRetries = 3
}
```

### Relevant files

[files.tar.gz](https://github.com/nf-core/sarek/files/9799133/files.tar.gz)

### System information

nextflow version 21.10.6.5660

Linux adsystems-System-Product-Name 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Executor: bash

Container Docker

sarek version 3.0.2

**Comment by paumarc** [comment]
it was  my fault, sorry for the inconvenient

**Comment by davidmasp** [comment]
Do you by any chance remember what was wrong? I am experiencing the same issue but I am not sure what I am doing wrong.
