### ISSUE TITLE
Workflow execution completed unsuccessfully! due to CNVkit error 

### ISSUE THREAD

**Issue by Ahas4** [nf-core/sarek#920]
### Description of the bug

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

```
Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_CNVKIT:CNVKIT_BATCH (Tumour_17_vs_Normal_17)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_CNVKIT:CNVKIT_BATCH (Tumour_17_vs_Normal_17)` terminated with an error exit status (1)

Command executed:

  samtools view -T Homo_sapiens_assembly38.fasta --fai-reference Homo_sapiens_assembly38.fasta.fai Tumour_17.recal.cram -@ 2 -o Tumour_17.recal.bam
  samtools view -T Homo_sapiens_assembly38.fasta --fai-reference Homo_sapiens_assembly38.fasta.fai Normal_17.recal.cram -@ 2 -o Normal_17.recal.bam
  
  cnvkit.py \
      batch \
      Tumour_17.recal.bam \
      --normal Normal_17.recal.bam \
      --fasta Homo_sapiens_assembly38.fasta \
       \
      --targets target_sorted.unique.bed \
      --processes 2 \
      --method hybrid --diagram --scatter
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_SOMATIC_ALL:BAM_VARIANT_CALLING_CNVKIT:CNVKIT_BATCH":
      samtools: $(echo $(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*$//')
      cnvkit: $(cnvkit.py version | sed -e "s/cnvkit v//g")
  END_VERSIONS

Command exit status:
  1

Command output:
  
  ++ stat mem=29517 3 516464 350016 800812 631652 276395 358
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 3 521956 351624 806308 633260 276399 359
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=29517 2 474128 307576 800812 631652 315706 395
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 2 479620 309184 806308 633260 315710 396
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=29517 2 456656 287816 800812 631652 356130 456
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 2 462148 289424 806308 633260 356134 457
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=29517 2 455188 289764 800812 631652 396869 495
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 2 460680 291372 806308 633260 396873 496
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=29517 2 381552 216128 800812 631652 437476 530
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 2 387044 217736 806308 633260 437480 531
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=29517 1 354908 197508 800812 631652 477966 571
  ++ stat mem=31450 0 5492 1608 5496 1608 4 1
  ++ stat SUM=0 1 360400 199116 806308 633260 477970 572
  ++ stat PEAK=0 4 680268 502784 830252 652956 911544 3077
  
  ++ stat mem=4143 2 2366912 260944 2376880 270528 1798 42
  ++ stat mem=31450 0 5492 1608 5496 1608 5 1
  ++ stat SUM=0 2 2372404 262552 2382376 272136 1803 43
  ++ stat PEAK=0 4 2372404 502784 2382376 652956 911544 3077
  
  ++ stat mem=4143 2 2496980 260012 2562516 270528 1830 46
  ++ stat mem=4312 2 2365908 234812 2365908 234812 9 154
  ++ stat mem=4313 2 2365908 234812 2365908 234812 19 122
  ++ stat mem=31450 0 5492 1608 5496 1608 5 1
  ++ stat SUM=0 6 7234288 731244 7299828 741760 1863 323
  ++ stat PEAK=0 6 7234288 731244 7299828 741760 911544 3077
  
  ++ stat mem=4143 2 2496980 260012 2562516 270528 1830 46
  ++ stat mem=4312 2 2365908 234812 2365908 234812 11 299
  ++ stat mem=4313 2 2365908 234812 2365908 234812 21 259
  ++ stat mem=31450 0 5492 1608 5496 1608 5 1
  ++ stat SUM=0 6 7234288 731244 7299828 741760 1867 605
  ++ stat PEAK=0 6 7234288 731244 7299828 741760 911544 3077

Command error:
  WARNING: While bind mounting '/scratch/wsspaces/ahasan-VC_Sarek-0/db/a3e8338d2f0eef52ec3b1fab859404:/scratch/wsspaces/ahasan-VC_Sarek-0/db/a3e8338d2f0eef52ec3b1fab859404': destination is already in the mount point list
  /usr/local/lib/python3.10/site-packages/skgenome/intersect.py:11: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
    from pandas import Int64Index
  CNVkit 0.9.9
  Detected file format: bed
  Splitting large targets
  Wrote ./target_sorted.unique.target.bed with 226032 regions
  /usr/local/lib/python3.10/site-packages/skgenome/intersect.py:39: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
    other_chroms = {c: o for c, o in other.groupby(['chromosome'], sort=False)}
  /usr/local/lib/python3.10/site-packages/skgenome/intersect.py:40: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
    for chrom, ctable in table.groupby(['chromosome'], sort=False):
  Wrote ./target_sorted.unique.antitarget.bed with 39266 regions
  Building a copy number reference from normal samples...
  [E::idx_find_and_load] [E::idx_find_and_load] Could not retrieve index file for 'Normal_17.recal.bam'Could not retrieve index file for 'Normal_17.recal.bam'
  
  Indexing BAM file Normal_17.recal.bam
  Indexing BAM file Normal_17.recal.bam
  Processing reads in Normal_17.recal.bam
  corrupted size vs. prev_size in fastbins
  Processing reads in Normal_17.recal.bam
  Traceback (most recent call last):
    File "/usr/local/bin/cnvkit.py", line 9, in 
      args.func(args)
    File "/usr/local/lib/python3.10/site-packages/cnvlib/commands.py", line 110, in _cmd_batch
      args.reference, args.targets, args.antitargets = batch.batch_make_reference(
    File "/usr/local/lib/python3.10/site-packages/cnvlib/batch.py", line 139, in batch_make_reference
      target_fnames = [tf.result() for tf in tgt_futures]
    File "/usr/local/lib/python3.10/site-packages/cnvlib/batch.py", line 139, in 
      target_fnames = [tf.result() for tf in tgt_futures]
    File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
      return self.__get_result()
    File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
      raise self._exception
  concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Work dir:
  /scratch/wsspaces/ahasan-VC_Sarek-0/db/a3e8338d2f0eef52ec3b1fab859404

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.1.2 -profile singularity -c nextflow.config --input Samplesheet1.csv -w /scratch/wsspaces/ahasan-VC_Sarek-0 --genome GATK.GRCh38 --wes --intervals /data/cpo/ahasan/VC_Sarek/target_sorted.unique.bed --tools cnvkit,freebayes,manta,mpileup,mutect2,tiddit,deepvariant,haplotypecaller,strelka,ascat,msisensorpro,vep,snpeff
```

### Relevant files
```
// Perform work directory cleanup after a successful run
cleanup = true

singularity {
    enabled = true
    autoMounts = true
    cacheDir = "/data/cpo/ahasan/VC_Sarek/nf_core_singularity_cache/"
    NFX_SINGULARITY_CACHEDIR = "/data/cpo/ahasan/VC_Sarek/singularity_cache/"
}

process {
    beforeScript =  """
        ml apps/singularity/3.8.0
        ml compilers/java/11.0.1
        ml apps/nextflow/21.10.5
        ml apps/python/3.8.6
        ml compilers/gcc/7.4.0
        """
    executor = 'pbs'
    queueStatInterval = '2min'
    pollInterval = '2min'

    // common SGE error statuses
    errorStrategy = {task.exitStatus in [143,137,104,134,139,140] ? 'retry' : 'finish'}
    maxErrors = '-1'
    maxRetries = 3
}

env {
  NXF_OPTS="Xms1g -Xmx1g"
  NXF_DEBUG="1"
}
```
### System information

nextflow/21.10.5

singularity/3.8.0

**Comment by ameynert** [comment]
I ran into this same issue - I solved it by indexing the BAM files prior to running CNVkit. I think it's an issue where running on 2 threads it's attempting to index the same BAM file at the same time. I'll post a bugfix to the module.

**Comment by FriederikeHanssen** [comment]
😱 thanks for the sleuthing 🔍  and fixing it ❤️
