### ISSUE TITLE
DeepVariant: Mismatching input samples

### ISSUE THREAD

**Issue by sandragold** [nf-core/sarek#946]
### Description of the bug

When running Sarek pipeline it errors on the process "MERGE_DEEPVARIANT_VCF". I couldn't find any advises anywhere to fix this problem and what Error exit status (3) means.

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.1 \
--input "/mnt/polkanowa2/nf-core_sarek_tests/input_1000genomes/samplesheet.csv" \
--genome GATK.GRCh38 \
--igenomes_base "/mnt/polkanowa2/nf-core_sarek_tests/references/" \
-profile docker \
--max_cpus 100 \
--max_memory '400.GB' \
--max_time '2400.day' \
-c config_increased_time \
--vep_dbnsfp \
--vep_spliceregion \
--save_bam_mapped \
--save_trimmed \
--save_reference \
--tools vep,deepvariant,haplotypecaller \
--wes \
--outdir /mnt/polkanowa2/nf-core_sarek_tests/outdir_references_run_nextflow -with-report report.html \
-resume loving_joliot \
-ansi-log false -dump-channels


config:
process {
     time = 2400.day
     withName:'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_HAPLOTYPECALLER:VCF_VARIANT_FILTERING_GATK:CNNSCOREVARIANTS'
}



OUTPUT:


[34/ff12df] Submitted process > NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_HAPLOTYPECALLER:VCF_VARIANT_FILTERING_GATK:CNNSCOREVARIANTS (sample2)

Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_DEEPVARIANT:MERGE_DEEPVARIANT_VCF (sample2)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_DEEPVARIANT:MERGE_DEEPVARIANT_VCF (sample2)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx4g" MergeVcfs \
      --INPUT sample2.deepvariant.chr2_97489619-238903659.vcf.gz --INPUT sample2.deepvariant.chr12_7084651-34719407.vcf.gz --INPUT sample2.deepvariant.chr13_86252980-111703855.vcf.gz --I>
      --OUTPUT sample2.deepvariant.vcf.gz \
      --SEQUENCE_DICTIONARY Homo_sapiens_assembly38.dict \
      --TMP_DIR . \


  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_DEEPVARIANT:MERGE_DEEPVARIANT_VCF":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  3

Command output:
  (empty)

Command error:
  Using GATK jar /usr/local/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx4g -jar /usr/loc>
  08:07:02.573 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.3.0.0-0/gatk-package-4.3.0.0-local.jar!/com/intel/gkl/native/libgkl_compre>
  [Mon Feb 13 08:07:02 GMT 2023] MergeVcfs --INPUT sample2.deepvariant.chr2_97489619-238903659.vcf.gz --INPUT sample2.deepvariant.chr12_7084651-34719407.vcf.gz --INPUT sample2.deepvarian>
  [Mon Feb 13 08:07:02 GMT 2023] Executing as root@002a29a8c952 on Linux 5.4.0-132-generic amd64; OpenJDK 64-Bit Server VM 11.0.15-internal+0-adhoc..src; Deflater: Intel; Inflater: Intel>
  [Mon Feb 13 08:07:07 GMT 2023] picard.vcf.MergeVcfs done. Elapsed time: 0.09 minutes.
  Runtime.totalMemory()=696254464
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  java.lang.IllegalArgumentException: Input path sample1.deepvariant.chr20_30088349-30425128.vcf.gz has sample entries that don't match the other files.
        at picard.vcf.MergeVcfs.doWork(MergeVcfs.java:207)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:309)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:37)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

Work dir:
  /mnt/polkanowa2/nf-core_sarek_tests/work/60/52a7fb896cfa380813a0083a58aef6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Relevant files

[igenomes_run_increased_memory_with_config_time_13Feb.log](https://github.com/nf-core/sarek/files/10784711/igenomes_run_increased_memory_with_config_time_13Feb.log)

### System information

N E X T F L O W  ~  version 21.10.6
Hardware: HPC
Executor: local
Container engine: Docker
OS: Linux Ubuntu 20.04.4 LTS
Version of nf-core/sarek: 3.1

**Comment by FriederikeHanssen** [comment]
Hey! this bug has been adressed in #896 and is currently available on the `dev`branch :) to work around it with a released version, you could increase `--nucleotides_per_second` by quite a bit.
