### ISSUE TITLE
GATK4_GENOTYPEGVCFS error

### ISSUE THREAD

**Issue by paolo-kunderfranco** [nf-core/sarek#964]
### Description of the bug

Dear All, I am facing a problem almost at the end of sarek version 3.1 for germline detection.

Could you please provide me assistance and help me to fix it?

Many Thanks

```
Error executing process > 'NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_HAPLOTYPECALLER:BAM_JOINT_CALLING_GERMLINE_GATK:GATK4_GENOTYPEGVCFS (joint_variant_calling)'

Caused by:
  Process `NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_HAPLOTYPECALLER:BAM_JOINT_CALLING_GERMLINE_GATK:GATK4_GENOTYPEGVCFS (joint_variant_calling)` terminated with an error exit status (3)

Command executed:

  gatk --java-options "-Xmx72g" GenotypeGVCFs \
      --variant gendb://chr15_75430187-75430375.joint \
      --output chr15_75430187-75430375.vcf.gz \
      --reference Homo_sapiens_assembly38.fasta \
       \
      --dbsnp dbsnp_146.hg38.vcf.gz \
      --tmp-dir . \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SAREK:SAREK:BAM_VARIANT_CALLING_GERMLINE_ALL:BAM_VARIANT_CALLING_HAPLOTYPECALLER:BAM_JOINT_CALLING_GERMLINE_GATK:GATK4_GENOTYPEGVCFS":
      gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  3

Command output:
  (empty)

Command error:
  09:40:19.358 INFO  ProgressMeter -         chr16:173125              4.4                  7000           1581.1
  09:40:54.996 INFO  ProgressMeter -         chr16:689239              5.0                  8000           1593.2
  09:41:18.531 INFO  ProgressMeter -        chr16:1228922              5.4                  9000           1notypeGVCFs - GCS max retries/reopens: 20
  09:35:52.270 INFO  GenotypeGVCFs - Requester pays: disabled
  09:35:52.270 INFO  GenotypeGVCFs - Initializing engine
  09:35:52.515 INFO  FeatureManager - Using codec VCFCodec to read file file://dbsnp_146.hg38.vcf.gz
  09:35:52.983 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.4.3-6069e4a
  10:35:53.420 info  NativeGenomicsDB - pid=50075 tid=50076 No valid combination operation found for INFO field DB  - the field will NOT be part of INFO fields in the generated VCF records
  10:35:53.420 info  NativeGenomicsDB - pid=50075 tid=50076 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
  10:35:53.420 info  NativeGenomicsDB - pid=50075 tid=50076 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
  10:35:53.420 info  NativeGenomicsDB - pid=50075 tid=50076 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
  09:35:53.574 WARN  IndexUtils - Feature file "file://dbsnp_146.hg38.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
  09:35:53.632 WARN  IntelInflater - Zero Bytes Written : 0
  09:35:53.656 INFO  GenotypeGVCFs - Done initializing engine
  09:35:53.715 INFO  ProgressMeter - Starting traversal
  09:35:53.715 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
  09:35:57.795 WARN  InbreedingCoeff - InbreedingCoeff will not be calculated at position chr15:75617462 and possibly subsequent; at least 10 samples must have called genotypes
  09:36:57.808 INFO  ProgressMeter -       chr15:80404516              1.1                  1000            936.1
  09:37:27.218 INFO  ProgressMeter -       chr15:82810185              1.6                  2000           1283.4
  09:37:43.219 INFO  ProgressMeter -       chr15:84240410              1.8                  3000           1643.8
  09:38:14.300 INFO  ProgressMeter -       chr15:88516787              2.3                  4000           1707.2
  09:39:01.694 INFO  ProgressMeter -       chr15:90762967              3.1                  5000           1595.9
  09:39:56.454 INFO  ProgressMeter -      chr15:100880106              4.0                  6000           1483.1
  09:40:19.358 INFO  ProgressMeter -         chr16:173125              4.4                  7000           1581.1
  09:40:54.996 INFO  ProgressMeter -         chr16:689239              5.0                  8000           1593.2
  09:41:18.531 INFO  ProgressMeter -        chr16:1228922              5.4                  9000           1662.5
  09:41:45.137 INFO  ProgressMeter -        chr16:1614825              5.9                 10000           1707.4
  09:42:25.324 INFO  ProgressMeter -        chr16:2135576              6.5                 11000           1685.4
  09:42:34.686 INFO  GenotypeGVCFs - Shutting down engine
  GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.2129274370000011,Cpu time(s),0.12280140800000039
  [March 9, 2023 at 9:42:34 AM GMT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 6.71 minutes.
  Runtime.totalMemory()=3774873600
  java.lang.RuntimeException: GenomicsDB JNI Error: vector::_M_default_append
  	at org.genomicsdb.reader.GenomicsDBFeatureIterator.hasNext(GenomicsDBFeatureIterator.java:183)
  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
  	at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)
  	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1095)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
  	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
  	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
  	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
  	at org.broadinstitute.hellbender.Main.main(Main.java:289)

Work dir:
  /home/pkf/gendata2/bioinformatica/pkunderfranco/HSR/nfcore_germline/work/8a/d79afc6faf08b26227cf24d9a4204b

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

```

### Command used and terminal output

```console
nextflow run nf-core/sarek -profile singularity -c $wd/nextflow.config --input $wd/samplesheet/HUM.csv --outdir $wd/outdir_HUM_paired --genome GATK.GRCh38 --only_paired_variant_calling FALSE --wes TRUE --joint_germline TRUE --intervals $panel/Twist_Exome_RefSeq_targets_hg38.bed --tools haplotypecaller,manta,snpeff,vep,merge --save_output_as_bam TRUE -r 3.1 -resume
```

### Relevant files

[logfile.txt](https://github.com/nf-core/sarek/files/10932821/logfile.txt)

### System information

nextflow/22.10.4
graphviz/2.50.0
singularity/3.4.2
slurm

**Comment by FriederikeHanssen** [comment]
Hey! Not sure what happened here. there is an odd error message inn your log file:
```
java.lang.IllegalArgumentException: Not a valid history entry: `2023-03-06 12:26:35	1h 44m 16s	nauseous_poincare	ERR	0b7f0e2b6f0be7053838ba1884b2eb03e9f83f9e	dcb7ba67-8afc-495f-8040-2170d84af997	nextflow run nf-core/sarek -profile singularity -c /home/pkf/gendata2/bioinformatica/pkunderfranco/HSR/nfcore_germline/nextflow.config --input /h2023-03-06 15:59:08	-	fabulous_brattain	-	0b7f0e2b6f0be7053838ba1884b2eb03e9f83f9e	
```

Did anything get deleted during the run?
