### ISSUE TITLE
fgbio CallMolecularConsensusReads Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by smzt** [nf-core/sarek#990]
### Description of the bug

Hi,
I am trying to analyze with Sarek a few exomes with paired-end reads of 151nt, that incorporate UMIs in R1 reads. When executing fgbio CallMolecularConsensusReads fails because of a memory problem. 
I am running Sarek on an HPC cluster with a Slurm queuing system, which is equipped with large capacities. I have set the following parameters in the params.json file:

```
{
    "input": "\/home\/user\/UMP421_pipe2nextflow\/UMIs_paired_exomes\/config\/sample.csv",
    "outdir": "\/home\/user\/UMP421_pipe2nextflow\/UMIs_paired_exomes\/analysis",
    "wes": true,
    "intervals": "\/home\/user\/info\/panel_designs\/HyperExome\/target.bed",
    "tools": "mutect2,VEP",
    "trim_fastq": true,
    "umi_read_structure": "9M151T 151T",
    "vep_include_fasta": true,
    "max_cpus": 30,
    "max_memory": "400.GB",
    "multiqc_title": "4WES",
    "nucleotides_per_second": 100000 
}
```

In addition, in the nextflow.config file located in the running directory, I've also added the following lines:
```
process {
  executor = 'slurm'
  queue = 'long'
}
```

The queue long has almost 500GB of RAM, which should be enough to process one sample. 
I do not see any parameter in the fgbio command that is executed in Sarek related to memory usage  -Xms or -Xmx. 
```
#!/bin/bash -euo pipefail
fgbio \
    --tmp-dir=. \
    CallMolecularConsensusReads \
    -i 105-gm-1_umi-grouped.bam \
    -M 1 -S Coordinate \
    -o 105-gm-1_umi-consensus.bam

cat <<-END_VERSIONS > versions.yml
"NFCORE_SAREK:SAREK:FASTQ_CREATE_UMI_CONSENSUS_FGBIO:CALLUMICONSENSUS":
    fgbio: $( echo $(fgbio --version 2>&1 | tr -d '[:cntrl:]' ) | sed -e 's/^.*Version: //;s/\[.*$//')
END_VERSIONS
```

Running the fgbio command this ways with the same input files that failed in the execution worked:

```
singularity exec --bind /clinicfs/userhomes/user/UMP421_pipe2nextflow/UMIs_paired_exomes/  /home/user/test_jf/singularity/singularity-images/depot.galaxyproject.org-singularity-fgbio-2.0.2--hdfd78af_0.img fgbio -Xms500m -Xmx100g --tmp-dir=. CallMolecularConsensusReads -i /clinicfs/userhomes/user/UMP421_pipe2nextflow/UMIs_paired_exomes/scripts/work/45/7653a0168e64e6540c9acb610591bf/105-gm-1_umi-grouped.bam -M 1 -S Coordinate -o 105-gm-1_umi-consensus.bam
```

So I think  I need to include -Xms500m -Xmx100g flags in the fgbio command but I do not know how to do this with the available options in sarek. 

I would be grateful if someone could tell me how to solve the problem.

Thanks in advance.

Sheila

### Command used and terminal output

```console
$ module load Nextflow/22.10.7 Singularity/3.6.4-GCC-5.4.0-2.26
$ nextflow -bg run nf-core/sarek -r 3.1.2 -name paired_exomes -profile singularity -params-file /home/user/UMP421_pipe2nextflow/UMIs_paired_exomes/config/nf-local-params.json



This is the error message:
[2023/04/06 15:39:43 | CallMolecularConsensusReads | Info] processed    38,000,000 records.  Elapsed time: 00:16:37s.  Time for last 1,000,000:   26s.  Last read position: chr4:9,268,435.  Last read name: A00718:490:H3LN2DSX5:2:2234:21748:27132
[2023/04/06 15:40:23 | FgBioMain | Info] CallMolecularConsensusReads failed. Elapsed time: 17.31 minutes.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:281)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:866)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:840)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)
        at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.next(CommonsDef.scala:249)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$Lambda$437/0x000000010062f840.apply$mcV$sp(Unknown Source)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.next(BetterBufferedIterator.scala:63)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.foreach(BetterBufferedIterator.scala:61)
        at com.fulcrumgenomics.bam.Template$.apply(Bams.scala:147)
        at com.fulcrumgenomics.bam.Template$.apply(Bams.scala:133)
        at com.fulcrumgenomics.bam.Bams$$anon$1.next(Bams.scala:314)
        at com.fulcrumgenomics.bam.Bams$$anon$1.next(Bams.scala:310)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$Lambda$437/0x000000010062f840.apply$mcV$sp(Unknown Source)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
        at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
        at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
        at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
```

**Comment by FriederikeHanssen** [comment]
Hi! 
thanks for reporting, unfortunately it is not possible to add these parameters in this case, the need to be updated in the module in nf-core/modules. 

However, have you tried increasing the memory for this particular process? `--max_memory` just serves as a ceiling and does not increase memory for any process: https://nf-co.re/docs/usage/troubleshooting#my-pipeline-crashes-part-way-through-a-run-at-a-certain-step-with-a-non-0-exit-code

**Comment by FriederikeHanssen** [comment]
Was this resolved?

**Comment by FriederikeHanssen** [comment]
Massive modules update in #1663 adds the following line to all fgbio modules:

```
if (!task.memory) {
        log.info '[fgbio CallMolecularConsensusReads] Available memory not known - defaulting to 8GB. Specify process memory requirements to change this.'
    } else {
        mem_gb = task.memory.giga
    }
    if ("$grouped_bam" == "${prefix}.bam") error "Input and output names are the same, use \"task.ext.prefix\" to disambiguate!"
    """
    fgbio \\
        -Xmx${mem_gb}g \\
```

I believe this should address this issue. I will close this issue in the meantime. We can re-open it if the issue persists
